### ISSUE TITLE
NFL API data discussion

### ISSUE THREAD

**Issue by toddrob99** [toddrob99/mynflapi#1]
Moving conversation from derek-adair/nflgame issue 130 since we are getting off-topic there.

@BrianT71 I haven't been able to actually see any injury data yet. I just started looking at NFL data a couple months ago and the injuries list has always been null. I assume/hope it will be populated once the season starts. I have found that viewer/team/injuries is valid, but it requires a subselection. I tried injuries{id} but it returns null. If you know how to pull in injury info at the team level, I am interested to learn more.

I agree it's very strange for the ids to change every year. It definitely makes things more difficult. 

The roster status is confusing me. In the /v1/teams/<id> endpoint, before it started throwing a 500 error, I was getting a bunch of people with inactive status when I queried for Philadelphia and Washington (week 1 matchup). It had exactly the data I wanted. With the shield query it's only listing active players for both teams. I see Marquise Goodwin showing NWT status for the 49ers, but he's with the Eagles now. I also see Malcolm Jenkins still listed with ACT status in the results for the Eagles even though he's with the Saints. What a mess.

**Comment by BrianT71** [comment]
Using shield viewer/team, I'm seeing a bunch of duplicate players for guys that moved teams (20-30 of them) as they are still in their own old team roster as well as new. I'm hoping this will get cleaned up as the season starts. Seems like a lot of issues have surfaced as they migrated NFL.com to use the shield API vs the old JSON feeds. One other thing I noticed is that the roster pages on NFL.com are not making API queries. They are just rendering HTML server side to show the list of players and it does not contain the duplicates.

As for injuries, I was never able to use NFL.com for them in the past. Prior to using the JSON feeds for stats,etc, I was scraping data from Sportsline.com and used their injury report. When I migrated to NFL.com for stats, rosters and schedules I still used Sportsline for injuries. It's a bit messy to match up players in some cases but I once I manually sort out the new players (rookies) at the beginning of the year it works well. I do want to get the injury data from the API but it's a lower priority than an accurate roster.

**Comment by BrianT71** [comment]
I can get a valid query with injuries{id} under the /viewer/team endpoint (see below). It's returning null right now but hopefully once the season starts it will have some actual data. The same works when using the /viewer/teams (plural) endpoint.

https://api.nfl.com/v3/shield/?query=query%7Bviewer%7Bteam(id%3A%2210043800-2020-6de2-d4a8-fc8cf0e8a3ad%22)%7Bid%20fullName%20season%7bid%20season%7d%20injuries%7Bid%7D%7D%7D%7D&variables=null

**Comment by toddrob99** [comment]
I also found injuries{id} but I'm thinking there are other fields that will need to be included in the subselection. I just don't know what they are because the fields in the [injury model](https://api.nfl.com/docs/league/models/injury/index.html) don't work. I had the same thought/hope that it will start working when the season starts. Same with the /v1/teams/{id} endpoint where I have actually seen the roster status work how I expect.

Do you have any idea what `Name is null` might mean for this endpoint?

https://api.nfl.com/v1/teams/10044500-2020-647d-4ff7-d6a678d2a29d?fs={id,season,fullName,nickName,cityStateRegion,abbr,teamType,conference{abbr},division{abbr},standings{overallWins,overallLosses,overallTies,overallWinPct,divisionWins,divisionLosses,divisionTies,clinchDivision,clinchDivisionAndHomefield,clinchWildcard,clinchPlayoff,conferenceRank,divisionRank}}

```json
{
    "errorStatus": "500 Internal Server Error",
    "errorMessage": "Name is null"
}
```

The team id is the 2020 Eagles, from https://api.nfl.com/v1/teams?s={"$query":{"season":2020}}&fs={id,season,fullName,nickName,abbr,teamType,conference{abbr},division{abbr}}.

The same call does not throw an error for the 2019 team ids, e.g. https://api.nfl.com/v1/teams/10043700-2019-3e28-0cb1-4bbe9b06a082?fs={id,season,fullName,nickName,cityStateRegion,abbr,teamType,conference{abbr},division{abbr},standings{overallWins,overallLosses,overallTies,overallWinPct,divisionWins,divisionLosses,divisionTies,clinchDivision,clinchDivisionAndHomefield,clinchWildcard,clinchPlayoff,conferenceRank,divisionRank}}. 

```json
{
    "id": "10043700-2019-3e28-0cb1-4bbe9b06a082",
    "season": 2019,
    "fullName": "Philadelphia Eagles",
    "nickName": "Eagles",
    "abbr": "PHI",
    "cityStateRegion": "Philadelphia",
    "teamType": "TEAM",
    "conference": {
        "abbr": "NFC"
    },
    "division": {
        "abbr": "NCE"
    }
}
```

**Comment by BrianT71** [comment]
When I use the shield API to pull the Eagles 2020 ID, it shows 10043700-2020-3696-5a83-d88a44306b38. That's different from the one you show coming from the V1 query. However, the 2019 ID is the same as you show. I'm becoming convinced that the shield API is using a completely different dataset than the V1 starting in 2020 and things are breaking as a result of this. With the NFL.com pages moving to Shield API, I'm assuming it will be more likely to get corrected going forward.

As for the injuries endpoint, it would seem to me that once the season starts and there are official injury reports, there will be "player" nodes attached to this listing each player on the injury report. I guess we will see next week.

**Comment by toddrob99** [comment]
I get the same team id from v1 and shield. The v1 id I listed above was for the 2019 team id, to show that it does return data for team ids from prior years. 

There's no Name in my query, so I have no idea why it's throwing an error for the 2020 team ids saying `Name is null`.

**Comment by BrianT71** [comment]
> (https://api.nfl.com/v1/teams/10044500-2020-647d-4ff7-d6a678d2a29d?fs=%7Bid,season,fullName,nickName,cityStateRegion,abbr,teamType,conference%7Babbr%7D,division%7Babbr%7D,standings%7BoverallWins,overallLosses,overallTies,overallWinPct,divisionWins,divisionLosses,divisionTies,clinchDivision,clinchDivisionAndHomefield,clinchWildcard,clinchPlayoff,conferenceRank,divisionRank%7D%7D)

In this query, you show the eagles ID being 10044500-2020-647d-4ff7-d6a678d2a29d. I thought you said this was the 2020 ID you pulled from a V1 query. When I pull a 2020 ID for the eagles from shield, I get 10043700-2020-3696-5a83-d88a44306b38. Unless I'm misunderstanding you, there are 2 different 2020 IDs for the Eagles depending on which API you query. I do see the same ID for 2019 from both V1 and shield.

As for the Name issue, the fact that it's a 500 error is strange. That's usually an error by the server itself, not an API response.

**Comment by toddrob99** [comment]
No, 10044500-2020-647d-4ff7-d6a678d2a29d is the 2020 49ers. You referenced that team id when you pointed out a player in the shield query showing status other than ACT. I'm getting the same team id for 2020 Eagles from all 3 endpoints:

https://api.nfl.com/v3/shield/?query=query%7Bviewer%7Bteam(id%3A%2210043700-2020-3696-5a83-d88a44306b38%22)%7Bid%20abbreviation%20fullName%20id%20nickName%20cityStateRegion%20franchise%7Bid%20slug%20currentLogo%7Burl%7D%7D%20season%7Bid%20season%7D%20division%20players%7Bid%20status%20position%20jerseyNumber%20person%7BfirstName%20lastName%20displayName%20highSchool%7D%7D%20injuries%7Bid%7D%7D%7D%7D&variables=null
`10043700-2020-3696-5a83-d88a44306b38`

https://api.nfl.com/v1/games?s={"$query":{"week.season":2020,"week.seasonType":"REG","week.week":1}},"$take":20,"$skip":0}&fs={week{id,season,weekOrder,seasonType,week,weekType,name},id,type,lastModifiedDate,gameTime,gameStatus,homeTeam{id,season,fullName,nickName,cityStateRegion,abbr,teamType,conference{abbr},division{abbr}},visitorTeam{id,season,fullName,nickName,cityStateRegion,abbr,teamType,conference{abbr},division{abbr}},homeTeamScore,visitorTeamScore,networkChannel,venue{id,type,name}}
`10043700-2020-3696-5a83-d88a44306b38` (but season=Null)

https://api.nfl.com/v1/teams?s={"$query":{"season":2020}}&fs={id,season,fullName,nickName,abbr,teamType,conference{abbr},division{abbr}}
`10043700-2020-3696-5a83-d88a44306b38`

**Comment by BrianT71** [comment]
Got it.

At this point, I'm going to sit tight and see what happens next week as the official injury list start coming out and the rosters get set. Hopefully the first game night will help clear some things up too.

**Comment by toddrob99** [comment]
NFL fixed the issue with the /v1/teams/{id} endpoint for 2020 team ids. The below API call returns data now, including the (currently null/empty) player injury status and team injuries list.

`https://api.nfl.com/v1/teams/10043700-2020-3696-5a83-d88a44306b38?fs={id,season,fullName,nickName,abbr,type,cityStateRegion,conference{abbr},division{abbr},roster{id,type,firstName,lastName,displayName,homeTown,college{id,name,type},highSchool,activeRole,player,coach},injuries}`

**Comment by BrianT71** [comment]
I have a bunch of shield API queries setup in Postman and will see what they return (fingers crossed). I'm out of town right now but will be back home tomorrow to check on this.

**Comment by BrianT71** [comment]
Are you seeing players on multiple rosters in the v1 queries? I still have Hopkins on both Houston and Arizona with the shield query (and a dozen others with similar situation).

Also, the NFL.com injuries site (nfl.com/injuries) isn't showing anything. They should be showing injuries for the KC/HOU game by now.

**Comment by toddrob99** [comment]
I haven't noticed any issues with the rosters when I use the /v1/teams/{id} endpoint. 

I only see DeAndre Hopkins on the Arizona roster: https://api.nfl.com/v1/teams/10043800-2020-6de2-d4a8-fc8cf0e8a3ad?fs={id,season,fullName,nickName,abbr,type,cityStateRegion,conference{abbr},division{abbr},roster{id,type,firstName,lastName,displayName,homeTown,college{id,name,type},highSchool,activeRole,player,coach},injuries}

Not listed for Houston: https://api.nfl.com/v1/teams/10042120-2020-b48b-be99-9b4c2ef7c3c0?fs={id,season,fullName,nickName,abbr,type,cityStateRegion,conference{abbr},division{abbr},roster{id,type,firstName,lastName,displayName,homeTown,college{id,name,type},highSchool,activeRole,player,coach},injuries}

I don't know what NFL is doing with injury status. there are nodes under each player as well as the team level, and no data in any of them.

**Comment by toddrob99** [comment]
I'm seeing injury data in the v1 team endpoint now. Not sure I found all of the injury status fields, but here's what I found:

https://api.nfl.com/v1/teams/10043700-2020-3696-5a83-d88a44306b38?fs={id,season,fullName,nickName,abbr,type,cityStateRegion,conference{abbr},division{abbr},roster{id,type,firstName,lastName,displayName,homeTown,college{id,name,type},highSchool,activeRole,player,coach},injuries{status,injuryStatus,practiceStatus,type,person{id,firstName,lastName,displayName,activeRole,player}}}

**Comment by toddrob99** [comment]
Some of us working on reddit game thread bots have a discord server for sports data. Feel free to join: https://discord.gg/XYtmNGW
